export default {
    SET_NAME:"SET_NAME",
    GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
    GET_INPUT:"GET_INPUT",
    TOGGLE_SEARCH_RESULT:"TOGGLE_SEARCH_RESULT",
    GET_ADDRESS_PREDICTIONS:"GET_ADDRESS_PREDICTIONS",
    GET_SELETED_BOX:"GET_SELETED_BOX",
	GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
    GET_DISTANCE_MATRIX:"GET_DISTANCE_MATRIX",
    GET_DISTANCE_DIRECTION:"GET_DISTANCE_DIRECTION",
	GET_FARE:"GET_FARE",
    BOOK_CAR:"BOOK_CAR",
    CANCEL_BOOK_CAR:"CANCEL_BOOK_CAR",
    GET_NEARBY_DRIVERS:"GET_NEARBY_DRIVERS",
    BOOKING_CONFIRMED :"BOOKING_CONFIRMED"
};