export default {
    SET_NAME:"SET_NAME",
    GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
    UPDATE_LOCATION:"UPDATE_LOCATION",
    GET_INPUT:"GET_INPUT",
    TOGGLE_SEARCH_RESULT:"TOGGLE_SEARCH_RESULT",
    GET_ADDRESS_PREDICTIONS:"GET_ADDRESS_PREDICTIONS",
    SET_SELECTED_BOX:"SET_SELECTED_BOX",
	GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
    GET_DISTANCE_MATRIX:"GET_DISTANCE_MATRIX",
    GET_DISTANCE_DIRECTION:"GET_DISTANCE_DIRECTION",
	GET_FARE:"GET_FARE",
    BOOK_CAR:"BOOK_CAR",
    CHANGE_BOOKING_STATUS:"CHANGE_BOOKING_STATUS",
    GET_NEARBY_DRIVERS:"GET_NEARBY_DRIVERS",
    GET_NEARBY_BOOKINGS:"GET_NEARBY_BOOKINGS",
    BOOKING_CONFIRMED :"BOOKING_CONFIRMED"
};